
"""create app tables

Revision ID: d776ab29a494
Revises: e4ac815e8363
Create Date: 2025-10-17 20:20:22.436322

"""

# revision identifiers, used by Alembic.
revision = 'd776ab29a494'
down_revision = 'e4ac815e8363'
branch_labels = None
depends_on = None
from alembic import op
import sqlalchemy as sa

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('esn', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('location', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device'))
    )
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_esn'), ['esn'], unique=True)
        batch_op.create_index(batch_op.f('ix_device_id'), ['id'], unique=False)

    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.String(length=64), nullable=False),
    sa.Column('raw_payload', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], name=op.f('fk_message_device_id_device'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_message'))
    )
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_message_id'), ['message_id'], unique=False)

    op.create_table('reading',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('depth_cm', sa.Float(), nullable=False),
    sa.Column('moisture_pct', sa.Float(), nullable=True),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], name=op.f('fk_reading_device_id_device'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], name=op.f('fk_reading_message_id_message'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reading'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reading')
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_message_id'))

    op.drop_table('message')
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_id'))
        batch_op.drop_index(batch_op.f('ix_device_esn'))

    op.drop_table('device')
    # ### end Alembic commands ###
